version: '2'
services:
  mongo: 
    container_name: mongo
    image: mongo
    ports: 
    - "27017:27017"
  app:
    container_name: item-des-mz
    restart: always
    build: .
    ports:
    - "80:3009"
    links: 
    - mongo